version: 2016.0.0.{build}
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget-restore
build:
  verbosity: minimal

test_script:
- nuget install OpenCover -Version 4.6.166 -OutputDirectory packages

- .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe -targetargs:".\IndependentTests\Output\IndependentTests.dll --framework=net-4.5 --where "cat!=TimeBased"" -filter:"+[*]* -[*]*Test -[*]*Tests" -excludebyattribute:*.ExcludeFromCodeCoverage* -output:coverage.xml -mergeoutput -returntargetcode
- .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe -targetargs:".\IndependentTests\Output\IndependentTests.dll --framework=net-4.5 --where "cat==TimeBased"" -filter:"+[*]* -[*]*Test -[*]*Tests" -excludebyattribute:*.ExcludeFromCodeCoverage* -output:coverage.xml -mergeoutput -returntargetcode
- .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe -targetargs:".\SimulatorTests\Output\SimulatorTests.dll --framework=net-4.5" -filter:"+[*]* -[*]*Test -[*]*Tests" -excludebyattribute:*.ExcludeFromCodeCoverage* -output:coverage.xml -mergeoutput -returntargetcode

- cmd: >-

- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "coverage.xml"

on_success:
- ps: >-
    
    If (($env:APPVEYOR_REPO_BRANCH -eq "master") -and (!$env:APPVEYOR_PULL_REQUEST_NUMBER)) {

    nuget pack "$env:APPVEYOR_BUILD_FOLDER\CSharpRoboticsLibrary\CSharpRoboticsLib.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -Symbols

    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    }
